"""Build the Kaggle submission from what the agent actually imports. OFFLINE; no board is run.

Two forms of the same files, because whether "one file" is a competition rule or a habit of the
samples is not ours to decide (queued to Isaiah, 2026-10-06):

    out/tether_pkg/         the reached modules and the data files, as a directory
    out/tether_bundle.py    ONE file carrying the same bytes; on import it writes them beside
                            itself and puts that directory on sys.path

The module list is a CENSUS, not a list: the entry module is imported in a fresh interpreter and
every repo module it pulls in is taken. Imports made lazily inside functions are not seen here --
the fake-wrapper smoke run is the runtime census. The data files ARE a list (`DATA`), because a
file read at runtime leaves no trace in sys.modules; each one is checked to exist.

`arcengine` is never bundled: it comes from the competition's wheels (interface bug 4).

    python kaggle_bundle.py [entry_module] [out_dir]
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import shutil
import subprocess
import sys
import zlib

sys.dont_write_bytecode = True

ROOT = os.path.dirname(os.path.abspath(__file__))

# READ AT RUNTIME, RELATIVE TO A MODULE'S OWN FILE (F449). A table, so a new one is added here
# deliberately or it is not shipped -- and the check below refuses a row that does not exist.
DATA = (
    "docs/library-closure/ATOMS.md",        # composer.recipe_rows, condition.corpus_glosses
    "docs/library-closure/ATTRIBUTES.md",   # condition.corpus_glosses
    "library/atoms.json",                   # inherited
    "library/molecules.json",
    "library/tag_index.json",
    "library/domains.json",
    "library/agent_atoms.json",
)
NEVER = ("arcengine",)

_CENSUS = """
import json, os, sys
sys.dont_write_bytecode = True
root = os.getcwd()
before = set(sys.modules)
__import__(sys.argv[1])
out = []
for name, mod in sys.modules.items():
    f = getattr(mod, "__file__", None)
    if name in before or not f:
        continue
    if os.path.dirname(os.path.abspath(f)) == root:
        out.append(os.path.basename(f))
print(json.dumps(sorted(out)))
"""


def census(entry: str) -> list[str]:
    """The repo files a fresh interpreter loads when it imports `entry`."""
    r = subprocess.run([sys.executable, "-c", _CENSUS, entry], cwd=ROOT, capture_output=True,
                       text=True, env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"})
    if r.returncode != 0:
        raise SystemExit(f"census failed importing {entry}:\n{r.stderr}")
    files = json.loads(r.stdout.strip().splitlines()[-1])
    bad = [f for f in files if f.split(".")[0] in NEVER]
    if bad:
        raise SystemExit(f"would bundle {bad}, which must come from the wheels")
    return files


def build(entry: str = "tether_agent", out: str = "out") -> dict:
    files = census(entry) + list(DATA)
    missing = [f for f in files if not os.path.isfile(os.path.join(ROOT, f))]
    if missing:
        raise SystemExit(f"listed but absent: {missing}")
    out = os.path.join(ROOT, out)
    pkg = os.path.join(out, "tether_pkg")
    shutil.rmtree(pkg, ignore_errors=True)
    blobs = {}
    for rel in files:
        src = os.path.join(ROOT, rel)
        dst = os.path.join(pkg, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)
        with open(src, "rb") as fh:
            blobs[rel] = fh.read()
    digest = hashlib.sha256(b"".join(k.encode() + v for k, v in sorted(blobs.items()))).hexdigest()
    packed = {k: base64.b64encode(zlib.compress(v, 9)).decode() for k, v in sorted(blobs.items())}
    one = os.path.join(out, "tether_bundle.py")
    with open(one, "w", encoding="utf-8") as fh:
        fh.write(_ONE_FILE.format(digest=digest, entry=entry, n=len(packed),
                                  files=json.dumps(packed, indent=0)))
    return {"files": len(files), "modules": len(files) - len(DATA), "data": len(DATA),
            "digest": digest[:16], "bundle_bytes": os.path.getsize(one), "pkg": pkg, "one": one}


_ONE_FILE = '''"""tether, bundled: {n} files, content digest {digest}.
Generated by kaggle_bundle.py -- edit the sources, never this file. On import it writes the
files beside itself (once per digest) and puts that directory on sys.path, so every module reads
its data relative to its own file as it does in the repository."""
import base64 as _b64
import json as _json
import os as _os
import sys as _sys
import zlib as _zlib

_DIGEST = "{digest}"
_FILES = _json.loads(r"""{files}""")


def install(dest=None):
    here = _os.path.dirname(_os.path.abspath(__file__))
    dest = dest or _os.path.join(here, "_tether_" + _DIGEST[:12])
    stamp = _os.path.join(dest, ".complete")
    if not _os.path.isfile(stamp):
        for rel, blob in _FILES.items():
            path = _os.path.join(dest, rel)
            _os.makedirs(_os.path.dirname(path), exist_ok=True)
            with open(path, "wb") as fh:
                fh.write(_zlib.decompress(_b64.b64decode(blob)))
        with open(stamp, "w") as fh:
            fh.write(_DIGEST)
    if dest not in _sys.path:
        _sys.path.insert(0, dest)
    return dest


install()
from {entry} import *  # noqa: E402,F401,F403
'''


if __name__ == "__main__":
    entry = sys.argv[1] if len(sys.argv) > 1 else "tether_agent"
    out = sys.argv[2] if len(sys.argv) > 2 else "out"
    print(json.dumps(build(entry, out), indent=1))
