"""figtext: one text of the figures, so both seats quote from the same version.

    python conform/figtext.py --write DIR   regenerate docs/FIGURES_TEXT.md from the SVGs in DIR
    python conform/figtext.py --check DIR   exit 1 if docs/FIGURES_TEXT.md differs from DIR's SVGs
    python conform/figtext.py --quotes [FILE]  every figure quote in INDEX from F506 on (or in FILE,
                                            whole), matched EXACTLY against docs/FIGURES_TEXT.md;
                                            prints the misses. A miss is a row to read, not a
                                            verdict: anything else quoted on a figure's line is
                                            attributed to that figure. The self-test runs first.

Isaiah, 2026-10-09: make sure the seat and the reviewer read the same version of the figures. The
reviewer's 13:07Z manifest names the set; each file here carries both of its hashes (the original,
with any C2PA provenance block, and the block stripped, which is what the reviewer uploaded), so a
reader can tie this text to the bytes. One line per <text> element, tspans joined, in document
order: a sentence that wraps across two elements shows as two adjacent lines, which is where the
Fig 2 "push on it" quote was lost to a whole-line grep.
"""

from __future__ import annotations

import hashlib
import html
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "FIGURES_TEXT.md"
# anchor: the census rule's first entry (figures.py FIRST); earlier quotes predate the rule.
FIRST = 506
_META = re.compile(rb"<metadata>.*?</metadata>", re.S)
_TEXT = re.compile(r"<text\b[^>]*>(.*?)</text>", re.S)
_TAG = re.compile(r"<[^>]+>")


def name(path: Path) -> str:
    m = re.match(r"Figure_(\d+)_", path.name)
    if m:
        return f"Fig {int(m.group(1))}"
    return "Operators table" if "Operators" in path.name else "Symbols table"


def _order(path: Path) -> tuple[int, str]:
    m = re.match(r"Figure_(\d+)_", path.name)
    return (int(m.group(1)) if m else 99, path.name)


def lines(raw: bytes) -> list[str]:
    s = _META.sub(b"", raw).decode("utf-8")
    out = [html.unescape(_TAG.sub("", t)).strip() for t in _TEXT.findall(s)]
    return [x for x in out if x]


def render(folder: Path) -> str:
    svgs = sorted(folder.glob("*.svg"), key=_order)
    head = ["# The figures, as text", "",
            "Generated by `conform/figtext.py --write` from Isaiah's original SVGs (the set",
            "named in the reviewer's 2026-10-09 13:07Z manifest). Do not edit by hand.",
            "One line per SVG text element, in document order; a sentence that wraps shows as",
            "adjacent lines. `original` hashes the file as Isaiah gave it, `stripped` hashes it",
            "with the C2PA provenance block removed (the reviewer's upload).", ""]
    body = []
    for p in svgs:
        raw = p.read_bytes()
        stripped = _META.sub(b"", raw)
        body += [f"## {name(p)} -- {p.name}", "",
                 f"original {hashlib.sha256(raw).hexdigest()}  ",
                 f"stripped {hashlib.sha256(stripped).hexdigest()}", "", "```"]
        body += [f"{i:3d}  {t}" for i, t in enumerate(lines(raw), 1)]
        body += ["```", ""]
    return "\n".join(head + body)


def _ws(s: str) -> str:
    """Whitespace only: the extract joins a wrapped sentence's lines with one space."""
    return re.sub(r"\s+", " ", s).strip()


def corpus() -> dict[str, str]:
    """Each figure's text joined into one string, so a quote that wraps across elements is found."""
    out: dict[str, list[str]] = {}
    cur = None
    for ln in OUT.read_text(encoding="utf-8").splitlines():
        if ln.startswith("## "):
            cur = ln[3:].split(" -- ")[0]
            out[cur] = []
        elif cur and re.match(r"^\s*\d+  ", ln):
            out[cur].append(ln.split("  ", 1)[1])
    return {k: _ws(" ".join(v)) for k, v in out.items()}


_FIG = re.compile(r"Fig(?:ure)?\.?\s*(\d+)|(Operators table|Symbols table)")
_Q = re.compile(r"\"([^\"\n]{3,})\"")


def _attributed(body: str) -> list[tuple[str, str]]:
    """Every quote on a line that names a figure, attributed to the last figure named before it."""
    out = []
    for line in body.splitlines():
        marks = list(_FIG.finditer(line))
        for q in _Q.finditer(line):
            before = [m for m in marks if m.end() <= q.start()]
            if before:
                m = before[-1]
                out.append((f"Fig {int(m.group(1))}" if m.group(1) else m.group(2), q.group(1)))
    return out


def _found(fig: str, q: str, figs: dict[str, str]) -> bool:
    """EXACT: every fragment of the quote (split only at an elision) is a substring of the figure's
    text. Case, dashes and closing punctuation are the figure's, so a period the figure does not
    have is a miss (the reviewer, 2026-10-09 14:52Z: the checker must be able to refuse)."""
    frags = [f.strip() for f in re.split(r"\.\.\.|…", _ws(q)) if len(f.strip()) > 2]
    return fig in figs and bool(frags) and all(f in figs[fig] for f in frags)


def quotes(text: str, first: int = FIRST) -> list[tuple[int, str, str, bool]]:
    """Every figure quote in INDEX entries numbered `first` on; a text with no entries is one."""
    figs = corpus()
    marks = list(re.finditer(r"^#### F(\d+)\b", text, re.M))
    spans = [(int(m.group(1)), m.start(), marks[i + 1].start() if i + 1 < len(marks) else len(text))
             for i, m in enumerate(marks)] or [(first, 0, len(text))]
    return [(n, fig, q, _found(fig, q, figs))
            for n, a, b in spans if n >= first for fig, q in _attributed(text[a:b])]


def selftest() -> None:
    figs = {"Fig 9": "the witness is always imported → \"it is not in here\""}
    assert _found("Fig 9", "the witness is always imported", figs)
    assert not _found("Fig 9", "the witness is always imported.", figs)   # a period it lacks
    assert not _found("Fig 9", "The witness is always imported", figs)    # case is the figure's
    assert _found("Fig 9", "the witness ... imported", figs)              # an elision splits
    assert not _found("Fig 8", "the witness is always imported", figs)    # the figure named


def main(argv: list[str]) -> int:
    selftest()
    if len(argv) == 2 and argv[0] in ("--write", "--check"):
        new = render(Path(argv[1]))
        if argv[0] == "--write":
            OUT.write_text(new, encoding="utf-8", newline="\n")
            print(f"figtext: wrote {OUT.relative_to(ROOT)}")
            return 0
        same = OUT.exists() and OUT.read_text(encoding="utf-8") == new
        print("figtext: up to date" if same else "figtext: DIFFERS from the SVGs -- regenerate")
        return 0 if same else 1
    if argv[:1] == ["--quotes"] and len(argv) <= 2:
        src = Path(argv[1]) if len(argv) == 2 else ROOT / "docs" / "INDEX.md"
        rows = quotes(src.read_text(encoding="utf-8"))
        miss = [r for r in rows if not r[3]]
        for n, fig, q, _ in miss:
            print(f"F{n}  {fig}  NOT FOUND  \"{q}\"")
        print(f"figtext: {len(rows)} quotes from F{FIRST} on, {len(rows) - len(miss)} found, "
              f"{len(miss)} not found")
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
